// <auto-generated />
namespace LearnIt.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class CourseNamesCHanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CourseNamesCHanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201711101728280_CourseNamesCHanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
